version: '3.9'

services:
  app_imdb:
    container_name: app_imdb 
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app_imdb:/django-imdb/app_imdb 
    env_file:
      - ./.env
    depends_on:
      - psql

  psql:
    container_name: psql
    image: postgres:14-alpine3.22
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./.env